In [303]:
import pandas as pd
df = pd.read_csv("Covid19_Vaccines_Cleaned_Final(3).csv")

In [304]:
y = df.loc[:,"HOSPITAL"]

In [305]:
df

,Unnamed: 0,VAERS_ID,AGE_YRS,SEX,DIED,L_THREAT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,NUMDAYS,BIRTH_DEFECT,VAX_DOSE_SERIES,total,HISTORY1,OTHER_MEDS1,ALLERGIES1,Days_Bf_Dead,PFIZER\BIONTECH
0,0,916600,0.312649,0,0,0,0,0.000000,0,0,1,0.000054,0.0,1,0.01,0.0,0.0,1.0,0.000000,0
1,1,916601,0.694511,0,0,0,0,0.000000,0,0,1,0.000000,0.0,1,0.01,1.0,1.0,1.0,0.000000,0
2,2,916602,0.217184,0,0,0,0,0.000000,0,0,2,0.000000,0.0,1,0.03,0.0,0.0,1.0,0.000000,1
3,3,916603,0.551313,0,0,0,0,0.000000,0,0,1,0.000000,0.0,0,0.02,1.0,0.0,1.0,0.000000,0
4,4,916604,0.446301,0,0,0,0,0.000000,0,0,0,0.000190,0.0,1,0.03,0.0,0.0,0.0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7757,9114,1034158,0.732697,1,0,0,1,0.027778,0,0,1,0.000000,0.0,1,0.22,1.0,1.0,0.0,0.032609,0
7758,9115,1034182,0.780430,1,1,0,1,0.277778,0,0,0,0.000081,0.0,1,0.15,0.0,0.0,0.0,0.002717,1
7759,9116,1034192,0.704057,0,1,0,1,0.361111,0,0,0,0.000054,0.0,0,0.04,1.0,1.0,0.0,0.002717,0
7760,9117,1034217,0.389021,0,0,1,0,0.000000,0,0,0,0.000027,0.0,2,0.06,1.0,1.0,1.0,0.000000,0
7761,9118,1034234,0.837709,0,0,0,0,0.000000,0,1,0,0.000000,0.0,0,0.04,1.0,1.0,1.0,0.010870,1

In [314]:
df.query("AGE_YRS <= 0.43 & AGE_YRS > 0.38")

,Unnamed: 0,VAERS_ID,AGE_YRS,SEX,DIED,L_THREAT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,NUMDAYS,BIRTH_DEFECT,VAX_DOSE_SERIES,total,HISTORY1,OTHER_MEDS1,ALLERGIES1,Days_Bf_Dead,PFIZER\BIONTECH
5,5,916606,0.417661,0,0,0,0,0.000000,0,0,1,0.000000,0.0,1,0.00,0.0,0.0,1.0,0.000000,0
22,22,916625,0.389021,0,0,0,0,0.000000,0,0,1,0.000000,0.0,1,0.05,1.0,1.0,1.0,0.000000,1
34,34,916638,0.389021,1,0,0,0,0.000000,0,0,0,0.000027,0.0,2,0.03,1.0,1.0,0.0,0.000000,1
37,37,916642,0.398568,0,0,0,0,0.000000,0,0,1,0.000000,0.0,1,0.05,0.0,0.0,1.0,0.000000,0
42,42,916647,0.398568,1,0,0,0,0.000000,0,0,1,0.000000,0.0,0,0.05,1.0,1.0,0.0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7731,9088,1033581,0.427208,0,0,0,1,0.111111,0,0,1,0.000027,0.0,2,0.06,0.0,0.0,0.0,0.000000,0
7735,9092,1033614,0.398568,0,0,0,1,0.000000,0,0,0,0.000190,0.0,1,0.19,0.0,0.0,0.0,0.000000,0
7741,9098,1033768,0.398568,0,0,1,1,0.000000,0,0,1,0.000136,0.0,2,0.06,1.0,1.0,1.0,0.000000,1
7755,9112,1034125,0.417661,0,0,1,0,0.000000,0,0,0,0.000000,0.0,1,0.05,1.0,0.0,0.0,0.067935,1
7760,9117,1034217,0.389021,0,0,1,0,0.000000,0,0,0,0.000027,0.0,2,0.06,1.0,1.0,1.0,0.000000,0

In [316]:
df.describe()

,Unnamed: 0,VAERS_ID,AGE_YRS,SEX,DIED,L_THREAT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,NUMDAYS,BIRTH_DEFECT,VAX_DOSE_SERIES,total,HISTORY1,OTHER_MEDS1,ALLERGIES1,Days_Bf_Dead,PFIZER\BIONTECH
count,7762.000000,7.762000e+03,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000
mean,4399.404406,9.573880e+05,0.504768,0.289230,0.105643,0.084772,0.262948,0.017417,0.002705,0.048956,0.611827,0.000448,0.004123,1.021000,0.047421,0.494589,0.529889,0.354934,0.002091,0.492270
std,2704.918205,4.013685e+04,0.187204,0.453434,0.307400,0.278560,0.440263,0.055462,0.051947,0.215791,0.722156,0.014515,0.064079,0.574955,0.054427,0.500003,0.499138,0.478524,0.014779,0.499972
min,0.000000,9.166000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2000.250000,9.189505e+05,0.350835,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4323.500000,9.446640e+05,0.484487,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000027,0.000000,1.000000,0.030000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,6747.750000,9.941228e+05,0.646778,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000108,0.000000,1.000000,0.060000,1.000000,1.000000,1.000000,0.000000,1.000000
max,9118.000000,1.034234e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [307]:
df.query("HOSPITAL == 1 & HOSPDAYS==0.0 & DIED == 1").shape

(40, 20)

In [257]:
df.query("HOSPITAL == 1 & AGE_YRS >= 0.8").shape

(278, 20)

In [325]:
df.query("DIED==1 & AGE_YRS >= 0.40 & AGE_YRS <= 0.75 & L_THREAT == 0")

,Unnamed: 0,VAERS_ID,AGE_YRS,SEX,DIED,L_THREAT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,NUMDAYS,BIRTH_DEFECT,VAX_DOSE_SERIES,total,HISTORY1,OTHER_MEDS1,ALLERGIES1,Days_Bf_Dead,PFIZER\BIONTECH
1082,1108,917793,0.742243,0,1,0,0,0.000000,0,0,0,0.000190,0.0,1,0.02,0.0,1.0,0.0,0.000000,0
1330,1358,918065,0.608592,1,1,0,0,0.000000,0,0,0,0.000054,0.0,1,0.01,0.0,0.0,0.0,0.000000,0
1536,1568,918388,0.618138,0,1,0,0,0.000000,0,0,0,0.000054,0.0,1,0.04,0.0,1.0,0.0,0.000000,1
1559,1593,918418,0.618138,1,1,0,0,0.000000,0,0,0,0.000054,0.0,1,0.06,0.0,1.0,1.0,0.000000,1
1632,1667,918518,0.474940,0,1,0,0,0.000000,0,0,0,0.000000,0.0,1,0.04,0.0,0.0,0.0,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7709,9064,1033323,0.579952,1,1,0,0,0.000000,0,0,0,0.000813,0.0,1,0.00,1.0,1.0,1.0,0.000000,1
7733,9090,1033607,0.694511,1,1,0,0,0.000000,0,0,0,0.000027,0.0,2,0.01,1.0,1.0,0.0,0.040761,0
7750,9107,1034055,0.494033,1,1,0,1,0.055556,0,0,0,0.000027,0.0,2,0.01,1.0,1.0,1.0,0.010870,1
7754,9111,1034116,0.551313,0,1,0,0,0.000000,0,0,0,0.000298,0.0,2,0.06,1.0,0.0,0.0,0.005435,1
7759,9116,1034192,0.704057,0,1,0,1,0.361111,0,0,0,0.000054,0.0,0,0.04,1.0,1.0,0.0,0.002717,0

In [258]:
df.query("HOSPITAL == 1 & HOSPDAYS <= 1.0 & DIED == 1 & HISTORY1 == 0").shape

(39, 20)

In [259]:
df.query("HOSPITAL == 1 & HOSPDAYS <= 1.0 & DIED == 1").shape

(137, 20)

In [260]:
y

0       0
1       0
2       0
3       0
4       0
       ..
7757    1
7758    1
7759    1
7760    0
7761    0
Name: HOSPITAL, Length: 7762, dtype: int64

In [261]:
df.head()

,Unnamed: 0,VAERS_ID,AGE_YRS,SEX,DIED,L_THREAT,HOSPITAL,HOSPDAYS,X_STAY,DISABLE,RECOVD,NUMDAYS,BIRTH_DEFECT,VAX_DOSE_SERIES,total,HISTORY1,OTHER_MEDS1,ALLERGIES1,Days_Bf_Dead,PFIZER\BIONTECH
0,0,916600,0.312649,0,0,0,0,0.0,0,0,1,0.000054,0.0,1,0.01,0.0,0.0,1.0,0.0,0
1,1,916601,0.694511,0,0,0,0,0.0,0,0,1,0.000000,0.0,1,0.01,1.0,1.0,1.0,0.0,0
2,2,916602,0.217184,0,0,0,0,0.0,0,0,2,0.000000,0.0,1,0.03,0.0,0.0,1.0,0.0,1
3,3,916603,0.551313,0,0,0,0,0.0,0,0,1,0.000000,0.0,0,0.02,1.0,0.0,1.0,0.0,0
4,4,916604,0.446301,0,0,0,0,0.0,0,0,0,0.000190,0.0,1,0.03,0.0,0.0,0.0,0.0,0

In [262]:
df.columns

Index(['Unnamed: 0', 'VAERS_ID', 'AGE_YRS', 'SEX', 'DIED', 'L_THREAT',
       'HOSPITAL', 'HOSPDAYS', 'X_STAY', 'DISABLE', 'RECOVD', 'NUMDAYS',
       'BIRTH_DEFECT', 'VAX_DOSE_SERIES', 'total', 'HISTORY1', 'OTHER_MEDS1',
       'ALLERGIES1', 'Days_Bf_Dead', 'PFIZER\BIONTECH'],
      dtype='object')

In [326]:
X = df.drop(columns=["Unnamed: 0","HOSPITAL","DIED","L_THREAT","HOSPDAYS","X_STAY", "RECOVD", "Days_Bf_Dead","VAERS_ID"])

In [327]:
X

,AGE_YRS,SEX,DISABLE,VAX_DOSE_SERIES,HISTORY1,OTHER_MEDS1,ALLERGIES1,PFIZER\BIONTECH
0,0.312649,0,0,1,0.0,0.0,1.0,0
1,0.694511,0,0,1,1.0,1.0,1.0,0
2,0.217184,0,0,1,0.0,0.0,1.0,1
3,0.551313,0,0,0,1.0,0.0,1.0,0
4,0.446301,0,0,1,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...
7757,0.732697,1,0,1,1.0,1.0,0.0,0
7758,0.780430,1,0,1,0.0,0.0,0.0,1
7759,0.704057,0,0,0,1.0,1.0,0.0,0
7760,0.389021,0,0,2,1.0,1.0,1.0,0
7761,0.837709,0,1,0,1.0,1.0,1.0,1

In [328]:
X.describe()

,AGE_YRS,SEX,DISABLE,VAX_DOSE_SERIES,HISTORY1,OTHER_MEDS1,ALLERGIES1,PFIZER\BIONTECH
count,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000,7762.000000
mean,0.504768,0.289230,0.048956,1.021000,0.494589,0.529889,0.354934,0.492270
std,0.187204,0.453434,0.215791,0.574955,0.500003,0.499138,0.478524,0.499972
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.350835,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,0.484487,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
75%,0.646778,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,7.000000,1.000000,1.000000,1.000000,1.000000

In [329]:
pd.set_option("display.max_columns",None)

In [330]:

from sklearn.model_selection import train_test_split

#SPLIT DATA INTO TRAIN AND TEST SET
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size =0.30, #by default is 75%-25%
                                                    #shuffle is set True by default,
                                                    stratify=None, #preserve target proportions 
                                                    random_state= 123) #fix random seed for replicability

print(X_train.shape, X_test.shape)

(5433, 8) (2329, 8)

In [331]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='gini', max_depth=3, min_samples_split=2, min_samples_leaf=2)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [332]:
y_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [333]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[1705   13]
 [ 597   14]]

In [334]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np

classifier = DecisionTreeClassifier()
parameters = {'criterion': ['entropy','gini'], 
              'max_depth': [3,5,10, 50],
              'min_samples_split': [5,10],
              'min_samples_leaf': [2,4]}

In [335]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(classifier, parameters, cv=3, scoring = 'f1', verbose=10, n_jobs=-1)

In [336]:
gs = gs.fit(X_train, y_train)

Fitting 3 folds for each of 32 candidates, totalling 96 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    5.7s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    5.8s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    5.8s
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    5.9s
[Parallel(n_jobs=-1)]: Batch computation too fast (0.1973s.) Setting batch_size=2.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    6.0s
[Parallel(n_jobs=-1)]: Batch computation too fast (0.0615s.) Setting batch_size=4.
[Parallel(n_jobs=-1)]: Batch computation too fast (0.1286s.) Setting batch_size=8.
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    6.1s
[Parallel(n_jobs=-1)]: Done  85 tasks      | elapsed:    6.3s
[Parallel(n_jobs=-1)]: Done  96 out of  96 | elapsed:    6.4s finished

In [337]:
print('***GRIDSEARCH RESULTS***')

print("Best score: %f using %s" % (gs.best_score_, gs.best_params_))
means = gs.cv_results_['mean_test_score']
stds = gs.cv_results_['std_test_score']
params = gs.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

***GRIDSEARCH RESULTS***
Best score: 0.334605 using {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.046022 (0.033524) with: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.046022 (0.033524) with: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.046022 (0.033524) with: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.046022 (0.033524) with: {'criterion': 'entropy', 'max_depth': 3, 'min_samples_leaf': 4, 'min_samples_split': 10}
0.281718 (0.085426) with: {'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.281718 (0.085426) with: {'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.279871 (0.086231) with: {'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.277757 (0.088050) with: {'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 10}
0.287403 (0.027838) with: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.284745 (0.028672) with: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.274939 (0.014900) with: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.288206 (0.014784) with: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 10}
0.320991 (0.026815) with: {'criterion': 'entropy', 'max_depth': 50, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.325677 (0.014071) with: {'criterion': 'entropy', 'max_depth': 50, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.308607 (0.026089) with: {'criterion': 'entropy', 'max_depth': 50, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.322180 (0.027888) with: {'criterion': 'entropy', 'max_depth': 50, 'min_samples_leaf': 4, 'min_samples_split': 10}
0.046022 (0.033524) with: {'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.046022 (0.033524) with: {'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.046022 (0.033524) with: {'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.046022 (0.033524) with: {'criterion': 'gini', 'max_depth': 3, 'min_samples_leaf': 4, 'min_samples_split': 10}
0.276866 (0.085398) with: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.275995 (0.086070) with: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.273233 (0.088282) with: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.273233 (0.088282) with: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 10}
0.290558 (0.027349) with: {'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.293858 (0.027168) with: {'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.282387 (0.008970) with: {'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.292489 (0.011921) with: {'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 10}
0.318617 (0.023846) with: {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 2, 'min_samples_split': 5}
0.334605 (0.017819) with: {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 2, 'min_samples_split': 10}
0.307549 (0.031908) with: {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 4, 'min_samples_split': 5}
0.318503 (0.033743) with: {'criterion': 'gini', 'max_depth': 50, 'min_samples_leaf': 4, 'min_samples_split': 10}

In [338]:
best_model = gs.best_estimator_
y_pred = best_model.predict(X_test)

y_pred_train = best_model.predict(X_train)

In [339]:
y_pred

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [340]:
from sklearn import metrics

print('***RESULTS ON TRAIN SET***')
print("f1_score: ", metrics.f1_score(y_train, y_pred_train))
print("--")
print('***RESULTS ON TEST SET***')
print("f1_score: ", metrics.f1_score(y_test, y_pred))

***RESULTS ON TRAIN SET***
f1_score:  0.5877957658779576
--
***RESULTS ON TEST SET***
f1_score:  0.3536463536463536

In [341]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.88      0.82      1718
           1       0.45      0.29      0.35       611

    accuracy                           0.72      2329
   macro avg       0.62      0.58      0.59      2329
weighted avg       0.69      0.72      0.70      2329

In [342]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[1505  213]
 [ 434  177]]

In [343]:
df["HOSPITAL"].value_counts()

0    5721
1    2041
Name: HOSPITAL, dtype: int64

In [344]:
##KNN

In [345]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size =0.30, #by default is 75%-25%
                                                    #shuffle is set True by default,
                                                    stratify=y,
                                                    random_state= 123
                                                   ) #fix random seed for replicability

print(X_train.shape,X_test.shape)

(5433, 8) (2329, 8)

In [346]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

#Create KNN Classifier
knn3 = KNeighborsClassifier(n_neighbors=3)

#Train the model using the training sets
knn3.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn3.predict(X_test)

In [347]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [348]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[1414  303]
 [ 428  184]]

In [349]:
from sklearn import metrics

print('***RESULTS ON TEST SET***')
print("F1_score: ",metrics.f1_score(y_test, y_pred))
print("Accuracy",metrics.accuracy_score(y_test, y_pred))
print("Recall",metrics.recall_score(y_test, y_pred))

***RESULTS ON TEST SET***
F1_score:  0.33484986351228385
Accuracy 0.6861313868613139
Recall 0.3006535947712418

In [350]:
from sklearn.model_selection import GridSearchCV

#Create KNN Classifier
classifier = KNeighborsClassifier()
parameters = {'n_neighbors':np.arange(1,40)}

gs = GridSearchCV(classifier, parameters, cv=3, scoring = 'f1', verbose=90, n_jobs=-1, refit='f1')

In [351]:
gs = gs.fit(X_train, y_train)

Fitting 3 folds for each of 39 candidates, totalling 117 fits
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    4.9s
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    4.9s
[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    5.0s
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    5.1s
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    5.2s
[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    5.2s
[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    5.3s
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    5.4s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    5.4s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    5.4s
[Parallel(n_jobs=-1)]: Done  11 tasks      | elapsed:    5.5s
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:    5.6s
[Parallel(n_jobs=-1)]: Done  13 tasks      | elapsed:    5.6s
[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:    5.6s
[Parallel(n_jobs=-1)]: Done  15 tasks      | elapsed:    5.7s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    5.8s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    5.9s
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:    5.9s
[Parallel(n_jobs=-1)]: Done  19 tasks      | elapsed:    5.9s
[Parallel(n_jobs=-1)]: Done  20 tasks      | elapsed:    6.1s
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:    6.1s
[Parallel(n_jobs=-1)]: Done  22 tasks      | elapsed:    6.1s
[Parallel(n_jobs=-1)]: Done  23 tasks      | elapsed:    6.2s
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    6.3s
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    6.3s
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    6.4s
[Parallel(n_jobs=-1)]: Done  27 tasks      | elapsed:    6.4s
[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:    6.5s
[Parallel(n_jobs=-1)]: Done  29 tasks      | elapsed:    6.6s
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:    6.6s
[Parallel(n_jobs=-1)]: Done  31 tasks      | elapsed:    6.7s
[Parallel(n_jobs=-1)]: Done  32 tasks      | elapsed:    6.8s
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    6.8s
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    6.9s
[Parallel(n_jobs=-1)]: Done  35 tasks      | elapsed:    6.9s
[Parallel(n_jobs=-1)]: Done  36 tasks      | elapsed:    7.0s
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:    7.1s
[Parallel(n_jobs=-1)]: Done  38 tasks      | elapsed:    7.1s
[Parallel(n_jobs=-1)]: Done  39 tasks      | elapsed:    7.2s
[Parallel(n_jobs=-1)]: Done  40 tasks      | elapsed:    7.3s
[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed:    7.3s
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    7.3s
[Parallel(n_jobs=-1)]: Done  43 tasks      | elapsed:    7.4s
[Parallel(n_jobs=-1)]: Done  44 tasks      | elapsed:    7.5s
[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:    7.6s
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:    7.6s
[Parallel(n_jobs=-1)]: Done  47 tasks      | elapsed:    7.6s
[Parallel(n_jobs=-1)]: Done  48 tasks      | elapsed:    7.7s
[Parallel(n_jobs=-1)]: Done  49 tasks      | elapsed:    7.8s
[Parallel(n_jobs=-1)]: Done  50 tasks      | elapsed:    7.8s
[Parallel(n_jobs=-1)]: Done  51 tasks      | elapsed:    7.9s
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:    8.0s
[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:    8.1s
[Parallel(n_jobs=-1)]: Done  54 tasks      | elapsed:    8.2s
[Parallel(n_jobs=-1)]: Done  55 tasks      | elapsed:    8.3s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    8.4s
[Parallel(n_jobs=-1)]: Done  57 tasks      | elapsed:    8.6s
[Parallel(n_jobs=-1)]: Done  58 tasks      | elapsed:    8.6s
[Parallel(n_jobs=-1)]: Done  59 tasks      | elapsed:    8.7s
[Parallel(n_jobs=-1)]: Done  60 tasks      | elapsed:    8.8s
[Parallel(n_jobs=-1)]: Done  61 tasks      | elapsed:    9.0s
[Parallel(n_jobs=-1)]: Done  62 tasks      | elapsed:    9.1s
[Parallel(n_jobs=-1)]: Done  63 tasks      | elapsed:    9.1s
[Parallel(n_jobs=-1)]: Done  64 tasks      | elapsed:    9.4s
[Parallel(n_jobs=-1)]: Done  65 tasks      | elapsed:    9.5s
[Parallel(n_jobs=-1)]: Done  66 tasks      | elapsed:    9.6s
[Parallel(n_jobs=-1)]: Done  67 tasks      | elapsed:    9.6s
[Parallel(n_jobs=-1)]: Done  68 tasks      | elapsed:    9.8s
[Parallel(n_jobs=-1)]: Done  69 tasks      | elapsed:    9.9s
[Parallel(n_jobs=-1)]: Done  70 tasks      | elapsed:   10.1s
[Parallel(n_jobs=-1)]: Done  71 tasks      | elapsed:   10.1s
[Parallel(n_jobs=-1)]: Done  72 tasks      | elapsed:   10.2s
[Parallel(n_jobs=-1)]: Done  73 tasks      | elapsed:   10.4s
[Parallel(n_jobs=-1)]: Done  74 tasks      | elapsed:   10.5s
[Parallel(n_jobs=-1)]: Done  75 tasks      | elapsed:   10.5s
[Parallel(n_jobs=-1)]: Done  76 tasks      | elapsed:   10.6s
[Parallel(n_jobs=-1)]: Done  77 tasks      | elapsed:   10.8s
[Parallel(n_jobs=-1)]: Done  78 tasks      | elapsed:   10.9s
[Parallel(n_jobs=-1)]: Done  79 tasks      | elapsed:   11.0s
[Parallel(n_jobs=-1)]: Done  80 tasks      | elapsed:   11.1s
[Parallel(n_jobs=-1)]: Done  81 tasks      | elapsed:   11.3s
[Parallel(n_jobs=-1)]: Done  82 tasks      | elapsed:   11.3s
[Parallel(n_jobs=-1)]: Done  83 tasks      | elapsed:   11.4s
[Parallel(n_jobs=-1)]: Done  84 tasks      | elapsed:   11.5s
[Parallel(n_jobs=-1)]: Done  85 tasks      | elapsed:   11.6s
[Parallel(n_jobs=-1)]: Done  86 tasks      | elapsed:   11.8s
[Parallel(n_jobs=-1)]: Done  87 tasks      | elapsed:   11.8s
[Parallel(n_jobs=-1)]: Done  88 tasks      | elapsed:   11.9s
[Parallel(n_jobs=-1)]: Done  89 tasks      | elapsed:   12.1s
[Parallel(n_jobs=-1)]: Done  90 tasks      | elapsed:   12.1s
[Parallel(n_jobs=-1)]: Done  91 tasks      | elapsed:   12.2s
[Parallel(n_jobs=-1)]: Done  92 tasks      | elapsed:   12.3s
[Parallel(n_jobs=-1)]: Done  93 tasks      | elapsed:   12.5s
[Parallel(n_jobs=-1)]: Done  94 tasks      | elapsed:   12.6s
[Parallel(n_jobs=-1)]: Done  95 tasks      | elapsed:   12.7s
[Parallel(n_jobs=-1)]: Done  96 tasks      | elapsed:   12.7s
[Parallel(n_jobs=-1)]: Done  97 tasks      | elapsed:   12.9s
[Parallel(n_jobs=-1)]: Done  98 tasks      | elapsed:   13.0s
[Parallel(n_jobs=-1)]: Done  99 tasks      | elapsed:   13.1s
[Parallel(n_jobs=-1)]: Done 100 tasks      | elapsed:   13.2s
[Parallel(n_jobs=-1)]: Done 101 tasks      | elapsed:   13.3s
[Parallel(n_jobs=-1)]: Done 102 tasks      | elapsed:   13.4s
[Parallel(n_jobs=-1)]: Done 103 tasks      | elapsed:   13.6s
[Parallel(n_jobs=-1)]: Done 104 tasks      | elapsed:   13.6s
[Parallel(n_jobs=-1)]: Done 105 tasks      | elapsed:   13.8s
[Parallel(n_jobs=-1)]: Done 106 tasks      | elapsed:   13.9s
[Parallel(n_jobs=-1)]: Done 107 tasks      | elapsed:   14.1s
[Parallel(n_jobs=-1)]: Done 108 tasks      | elapsed:   14.1s
[Parallel(n_jobs=-1)]: Done 109 tasks      | elapsed:   14.2s
[Parallel(n_jobs=-1)]: Done 110 tasks      | elapsed:   14.4s
[Parallel(n_jobs=-1)]: Done 112 out of 117 | elapsed:   14.6s remaining:    0.6s
[Parallel(n_jobs=-1)]: Done 114 out of 117 | elapsed:   14.8s remaining:    0.3s
[Parallel(n_jobs=-1)]: Done 117 out of 117 | elapsed:   15.1s finished

In [352]:
print("Best score: %f using %s" % (gs.best_score_, gs.best_params_))

means = gs.cv_results_['mean_test_score']
stds = gs.cv_results_['std_test_score']
params = gs.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("Mean %f Std (%f) with: %r" % (mean, stdev, param))

Best score: 0.361266 using {'n_neighbors': 1}
Mean 0.361266 Std (0.004305) with: {'n_neighbors': 1}
Mean 0.219681 Std (0.005673) with: {'n_neighbors': 2}
Mean 0.342394 Std (0.014385) with: {'n_neighbors': 3}
Mean 0.242994 Std (0.028466) with: {'n_neighbors': 4}
Mean 0.339393 Std (0.030554) with: {'n_neighbors': 5}
Mean 0.244514 Std (0.019405) with: {'n_neighbors': 6}
Mean 0.317750 Std (0.014152) with: {'n_neighbors': 7}
Mean 0.237686 Std (0.008516) with: {'n_neighbors': 8}
Mean 0.315527 Std (0.015318) with: {'n_neighbors': 9}
Mean 0.240250 Std (0.006662) with: {'n_neighbors': 10}
Mean 0.297335 Std (0.014385) with: {'n_neighbors': 11}
Mean 0.228525 Std (0.016800) with: {'n_neighbors': 12}
Mean 0.289635 Std (0.003635) with: {'n_neighbors': 13}
Mean 0.228323 Std (0.021898) with: {'n_neighbors': 14}
Mean 0.276492 Std (0.011450) with: {'n_neighbors': 15}
Mean 0.225049 Std (0.020890) with: {'n_neighbors': 16}
Mean 0.276137 Std (0.001111) with: {'n_neighbors': 17}
Mean 0.222725 Std (0.013689) with: {'n_neighbors': 18}
Mean 0.261775 Std (0.004867) with: {'n_neighbors': 19}
Mean 0.217814 Std (0.013046) with: {'n_neighbors': 20}
Mean 0.252446 Std (0.012677) with: {'n_neighbors': 21}
Mean 0.223711 Std (0.017070) with: {'n_neighbors': 22}
Mean 0.253892 Std (0.024831) with: {'n_neighbors': 23}
Mean 0.216013 Std (0.029838) with: {'n_neighbors': 24}
Mean 0.243551 Std (0.025171) with: {'n_neighbors': 25}
Mean 0.215406 Std (0.027344) with: {'n_neighbors': 26}
Mean 0.227530 Std (0.026971) with: {'n_neighbors': 27}
Mean 0.210720 Std (0.033969) with: {'n_neighbors': 28}
Mean 0.227950 Std (0.028292) with: {'n_neighbors': 29}
Mean 0.205671 Std (0.023104) with: {'n_neighbors': 30}
Mean 0.217018 Std (0.019515) with: {'n_neighbors': 31}
Mean 0.202164 Std (0.031973) with: {'n_neighbors': 32}
Mean 0.226900 Std (0.024090) with: {'n_neighbors': 33}
Mean 0.196127 Std (0.014839) with: {'n_neighbors': 34}
Mean 0.214818 Std (0.015086) with: {'n_neighbors': 35}
Mean 0.191961 Std (0.019450) with: {'n_neighbors': 36}
Mean 0.211232 Std (0.018607) with: {'n_neighbors': 37}
Mean 0.181284 Std (0.018781) with: {'n_neighbors': 38}
Mean 0.208593 Std (0.013079) with: {'n_neighbors': 39}

In [353]:
best_model = gs.best_estimator_

y_pred_train = best_model.predict(X_train)
y_pred = best_model.predict(X_test)

In [354]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [355]:
from sklearn import metrics 

print('***RESULTS ON TEST SET***')
print("precision: ", metrics.precision_score(y_test, y_pred)) # tp / (tp + fp)
print("recall: ", metrics.recall_score(y_test, y_pred)) # tp / (tp + fn)
print("f1_score: ", metrics.f1_score(y_test, y_pred)) #F1 = 2 * (precision * recall) / (precision + recall)
print("accuracy: ", metrics.accuracy_score(y_test, y_pred)) # (tp+tn)/m

***RESULTS ON TEST SET***
precision:  0.37777777777777777
recall:  0.3888888888888889
f1_score:  0.38325281803542677
accuracy:  0.6711034778875054

In [356]:
y_pred_train = best_model.predict(X_train)

print('***RESULTS ON TRAIN SET***')
print("precision: ", metrics.precision_score(y_train, y_pred_train)) # tp / (tp + fp)
print("recall: ", metrics.recall_score(y_train, y_pred_train)) # tp / (tp + fn)
print("f1_score: ", metrics.f1_score(y_train, y_pred_train)) #F1 = 2 * (precision * recall) / (precision + recall)
print("accuracy: ", metrics.accuracy_score(y_train, y_pred_train)) # (tp+tn)/m

***RESULTS ON TRAIN SET***
precision:  0.749822316986496
recall:  0.7382785164450665
f1_score:  0.744005641748942
accuracy:  0.8663721700717836

In [357]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.77      0.78      1717
           1       0.38      0.39      0.38       612

    accuracy                           0.67      2329
   macro avg       0.58      0.58      0.58      2329
weighted avg       0.67      0.67      0.67      2329

In [297]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[1466  251]
 [ 386  226]]

In [358]:
##Random Forest

In [359]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.3,
                                                    random_state=42)

In [360]:
from sklearn.ensemble import RandomForestRegressor 
from sklearn.model_selection import GridSearchCV
import numpy as np

regressor = RandomForestRegressor()
parameters = {"n_estimators":[5,10,100], "criterion": ['mae'], 
              "max_depth":[2,10], "min_samples_leaf": [0.1,0.3]}

gs = GridSearchCV(regressor, parameters, scoring='f1', cv=3)

In [361]:
from sklearn.ensemble import RandomForestRegressor 
import numpy as np

regressor = RandomForestRegressor()
parameters = {"n_estimators":[5,10,100], "criterion": ['mse'], 
              "min_samples_leaf": [0.1,0.3], "random_state" : [42]}

#DEFINE YOUR GRIDSEARCH 
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(regressor, parameters, cv=3) #with no params it reduces to a CV

gs = gs.fit(X_train,y_train)

#summarize the results of your GRIDSEARCH
print('***GRIDSEARCH RESULTS***')
print("Best score: %f using %s" % (gs.best_score_, gs.best_params_))
means = gs.cv_results_['mean_test_score']
stds = gs.cv_results_['std_test_score']
params = gs.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

***GRIDSEARCH RESULTS***
Best score: 0.072728 using {'criterion': 'mse', 'min_samples_leaf': 0.1, 'n_estimators': 100, 'random_state': 42}
0.071285 (0.010674) with: {'criterion': 'mse', 'min_samples_leaf': 0.1, 'n_estimators': 5, 'random_state': 42}
0.072313 (0.011015) with: {'criterion': 'mse', 'min_samples_leaf': 0.1, 'n_estimators': 10, 'random_state': 42}
0.072728 (0.012109) with: {'criterion': 'mse', 'min_samples_leaf': 0.1, 'n_estimators': 100, 'random_state': 42}
0.040831 (0.009567) with: {'criterion': 'mse', 'min_samples_leaf': 0.3, 'n_estimators': 5, 'random_state': 42}
0.040954 (0.009236) with: {'criterion': 'mse', 'min_samples_leaf': 0.3, 'n_estimators': 10, 'random_state': 42}
0.040606 (0.010356) with: {'criterion': 'mse', 'min_samples_leaf': 0.3, 'n_estimators': 100, 'random_state': 42}

In [362]:
gs.score(X_test, y_test)

0.10188475482944181